### PR TITLE
Update let_there_be_flight.xml

### PR DESCRIPTION
**Pull request by titonix**
Improves controls for M+KB

### CODE REVIEW

**Comment by jackhumbert** [comment]
Have you had a chance to try the roll/pitch keys? They only work in drone mode right now. They need to be separate keys from lift in order to have full control of the vehicle. If someone else that uses M&KB could confirm these settings are sensible (I really only play with a controller), that would be great :)

**Comment by titonix** [comment]
> Have you had a chance to try the roll/pitch keys? They only work in drone mode right now. They need to be separate keys from lift in order to have full control of the vehicle. If someone else that uses M&KB could confirm these settings are sensible (I really only play with a controller), that would be great :)

I always use Hover and Fly mode but I could try and see if its still good

**Comment by jackhumbert** [comment]
Mouse buttons 4 & 5 are the scroll wheel, right? I don't think that's something that's going to work for pitch - the keys are momentary adjustments, not positional changes. Having a positional change for both the roll & pitch would be an interesting option for the hover & fly mode, though!

**Comment by titonix** [comment]
> 

Mouse 4 and 5 are the side buttons on a mouse

**Comment by titonix** [comment]
Seems like Hover and Fly inverts the pitch buttons so I can only make it go down but not up, but it rolled when I flew off a cliff and pressed a & d

**Comment by jackhumbert** [comment]
For the drone mode on a keyboard, I think the only way it would really work is to have two hands on it - that's why I chose the buttons I did. The idea was that you could have your right hand on those keys to control both the roll & pitch together. Feel free to experiment with better combos, though!

**Comment by titonix** [comment]
Maybe there could be a way for Drone and hover mode to have separate inputs for more customizability?

**Pull request closed without merging**
